'use client'

import { Button } from '@/components/ui/button'
import { Download } from 'lucide-react'

type PaymentReceiptProps = {
  reference: string
  amount: number
  currency: string
  receiver: string
  description: string
  paidAt?: string
  method?: string
}

function formatReceiptDate(value?: string) {
  return new Intl.DateTimeFormat(undefined, {
    year: 'numeric',
    month: 'short',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
  }).format(value ? new Date(value) : new Date())
}

export function PaymentReceipt({
  reference,
  amount,
  currency,
  receiver,
  description,
  paidAt,
  method = 'Wallet',
}: PaymentReceiptProps) {
  const date = formatReceiptDate(paidAt)

  async function saveAsImage() {
    const canvas = document.createElement('canvas')
    const scale = 2
    const width = 420
    const height = 560
    canvas.width = width * scale
    canvas.height = height * scale

    const ctx = canvas.getContext('2d')
    if (!ctx) return

    ctx.scale(scale, scale)
    ctx.fillStyle = '#f8fafc'
    ctx.fillRect(0, 0, width, height)

    ctx.fillStyle = '#ffffff'
    roundRect(ctx, 24, 24, width - 48, height - 48, 18)
    ctx.fill()

    ctx.fillStyle = '#0f172a'
    ctx.font = 'bold 26px Arial'
    ctx.fillText('Payment receipt', 48, 72)

    ctx.fillStyle = '#16a34a'
    ctx.font = 'bold 40px Arial'
    ctx.fillText(`P${amount.toFixed(2)} ${currency}`, 48, 130)

    ctx.strokeStyle = '#e2e8f0'
    ctx.beginPath()
    ctx.moveTo(48, 164)
    ctx.lineTo(width - 48, 164)
    ctx.stroke()

    drawRow(ctx, 'Status', 'Successful', 200)
    drawRow(ctx, 'Paid to', receiver || 'Receiver', 248)
    drawRow(ctx, 'For', description || 'QR payment', 296)
    drawRow(ctx, 'Method', method, 344)
    drawRow(ctx, 'Date', date, 392)

    ctx.fillStyle = '#64748b'
    ctx.font = '12px Arial'
    ctx.fillText('Reference', 48, 454)

    ctx.fillStyle = '#0f172a'
    ctx.font = 'bold 14px Arial'
    wrapText(ctx, reference, 48, 478, width - 96, 18)

    ctx.fillStyle = '#94a3b8'
    ctx.font = '12px Arial'
    ctx.fillText('Generated by BotsPay', 48, height - 50)

    const filename = `epay-receipt-${reference || Date.now()}.png`
    const blob = await new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, 'image/png'))
    if (!blob) return

    const file = new File([blob], filename, { type: 'image/png' })
    if (navigator.canShare?.({ files: [file] })) {
      await navigator.share({
        files: [file],
        title: 'Payment receipt',
        text: 'Save or share your payment receipt.',
      })
      return
    }

    const link = document.createElement('a')
    link.href = URL.createObjectURL(blob)
    link.download = filename
    link.click()
    URL.revokeObjectURL(link.href)
  }

  return (
    <div className="space-y-4">
      <div className="rounded-lg border bg-white p-5 shadow-sm">
        <div className="flex items-start justify-between gap-4">
          <div>
            <p className="text-sm text-gray-500">Payment receipt</p>
            <h2 className="text-3xl font-bold mt-1">
              P{amount.toFixed(2)} {currency}
            </h2>
          </div>
          <span className="rounded-full bg-green-100 px-3 py-1 text-xs font-semibold text-green-800">
            Successful
          </span>
        </div>

        <div className="mt-5 divide-y text-sm">
          <ReceiptRow label="Paid to" value={receiver || 'Receiver'} />
          <ReceiptRow label="For" value={description || 'QR payment'} />
          <ReceiptRow label="Method" value={method} />
          <ReceiptRow label="Date" value={date} />
          <ReceiptRow label="Reference" value={reference} wrap />
        </div>
      </div>

      <Button type="button" onClick={saveAsImage} className="w-full">
        <Download className="mr-2 h-4 w-4" />
        Save receipt as image
      </Button>
    </div>
  )
}

function ReceiptRow({ label, value, wrap = false }: { label: string; value: string; wrap?: boolean }) {
  return (
    <div className="flex gap-4 py-3">
      <span className="w-24 shrink-0 text-gray-500">{label}</span>
      <span className={`font-medium text-gray-900 ${wrap ? 'break-all' : ''}`}>{value}</span>
    </div>
  )
}

function drawRow(CanvasCtx: CanvasRenderingContext2D, label: string, value: string, y: number) {
  CanvasCtx.fillStyle = '#64748b'
  CanvasCtx.font = '13px Arial'
  CanvasCtx.fillText(label, 48, y)

  CanvasCtx.fillStyle = '#0f172a'
  CanvasCtx.font = 'bold 15px Arial'
  wrapText(CanvasCtx, value, 150, y, 220, 18)
}

function wrapText(
  ctx: CanvasRenderingContext2D,
  text: string,
  x: number,
  y: number,
  maxWidth: number,
  lineHeight: number,
) {
  const words = String(text).split(' ')
  let line = ''

  for (const word of words) {
    const testLine = line ? `${line} ${word}` : word
    if (ctx.measureText(testLine).width > maxWidth && line) {
      ctx.fillText(line, x, y)
      line = word
      y += lineHeight
    } else {
      line = testLine
    }
  }
  ctx.fillText(line, x, y)
}

function roundRect(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, r: number) {
  ctx.beginPath()
  ctx.moveTo(x + r, y)
  ctx.arcTo(x + w, y, x + w, y + h, r)
  ctx.arcTo(x + w, y + h, x, y + h, r)
  ctx.arcTo(x, y + h, x, y, r)
  ctx.arcTo(x, y, x + w, y, r)
  ctx.closePath()
}
